#!/bin/bash

# find lastest houdini with (optional) given input
FINDSTR=/opt/hfs${1}\*
HDIR=$(find ${FINDSTR} -maxdepth 0 -type d | sort -nr | head -1)

# normal process
cd $HDIR
source houdini_setup
cd $OLDPWD
